<a href="https://colab.research.google.com/github/mcd-unison/material-programacion/blob/main/intro-python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center>
<p><img src="https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png" width="100">
</p>



# Curso Propedéutico en *Programación*

## Introducción a `python` resolviendo preguntas


**Julio Waissman Vilanova**



### Tipos

¿Cuales son los tipos de datos básicos? Revisa los tipos siguientes:

1. Tipos numéricos `int`, `float`, `complex`
2. Cadenas de caracteres
3. Tuplas
4. Listas
5. Diccionarios
6. Conjuntos

Da ejemplo de sobrecarga de operadores (en particular `+` y `*`)



In [ ]:
#Númerico y flotante
x = 33
y = 63.02

print(x + y)


#Cadenas de caracteres y númerico
z = 'manzana'
t = 7

print (z * t)

#lista y númerico
d = ("correr", "nadar", "saltar")
e = 4

print(d*e)

96.02000000000001
96.02000000000001
manzanamanzanamanzanamanzanamanzanamanzanamanzana
('correr', 'nadar', 'saltar', 'correr', 'nadar', 'saltar', 'correr', 'nadar', 'saltar', 'correr', 'nadar', 'saltar')


¿Que significa que unos tipos sean *mutables* y otros *inmutables*?

Realiza un pequeño programa donde quede claro lo que significa que un tipo de datos sea mutable, e ilustra el uso del método `copy.deepcopy()`.

In [ ]:
# los tipos de datos mutables son aquellos que se pueden modificar,
# inmutables son los que no pueden ser editados

import copy

frutas = ['manzana', 'pera', 'piña']
frutas = copy.deepcopy(frutas)

frutas.extend(["coco", "fresa", "banana"])

print(frutas)

##se le agregaron 3 elementos a la copia de la lista frutas

['manzana', 'pera', 'piña', 'coco', 'fresa', 'banana']


### *Comprehension* de listas, conjuntos y diccionarios

Escribe, en una sola linea, una expresión que genere una lista con todos los números enteros que se encuentran entre $1$ y $n$
que sean divisibles por $3$ y $7$ y que el dígito menos significativo del número sea $6$.

In [ ]:
n = 10_000

# Escribe aqui el *one linner*

NumEnt = [i for i in range(1, 1001) if i % 3 == 0 and i % 7 == 0 and str(i)[-1] == '6']

print(NumEnt)


[126, 336, 546, 756, 966]


### Funciones

Escribe una función que:

1. reciba una lista de elementos (letras, números, lo que sea),
2. cuente la ocurrencia de cada elemento en la lista,
3. devuelva las ocurrencias en forma de diccionario,
4. si imprime es True, imprima un histograma de ocurrencias, por ejemplo:

```python

lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]

d = funcion_ejemplo(lista, imprime = True)

1    		***** 	(5 -> 50%)
'a'  		***   	(3 -> 30%)
13		*	(1 -> 10%)
'hola'		*	(1 -> 10%)

```

In [ ]:

lista = [1,'a',1, 13, 'hola', 'a', 1, 1, 'a', 1]

from collections import Counter

    # Devolver el objeto Counter
print(Counter(lista))



Counter({1: 5, 'a': 3, 13: 1, 'hola': 1})


Escribe una función que modifique un diccionario y regrese el diccionario modificado y una copia del original, donde cada entrada
del diccionario sea una lista de valores. Ten en cuenta que si una entrada del diccionario es de tipo mutable, al modificarlo en la
copia se modifica el original. Utiliza el modulo `copy` para evitar este problema. Ejemplo de la función:

```python
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'febrero')

print(dic1)
{'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}

print(dic2)
{'Pepe':[12, 'febrero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
```

In [ ]:
# Escribe la función fundicos aquí

import copy

#se hizo una deep copy llamada dic2

dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = copy.deepcopy (dic1)

#se actualizó la copia agregandole un elemento
dic2.update({'edil' : ['07', 'octubre', '1994']})

#visualizar ambos diccionarios
print(dic1)
print(dic2)



{'Pepe': [12, 'enero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970]}
{'Pepe': [12, 'enero', 1980], 'Carolina': [15, 'mayo', 1975], 'Paco': [10, 'nov', 1970], 'edil': ['07', 'octubre', '1994']}


In [ ]:
# Realiza pruebas de fundicos aquí
dic1 = {'Pepe':[12, 'enero', 1980], 'Carolina':[15,'mayo',1975],'Paco':[10,'nov',1970]}
dic2 = fundicos(dic1, 'Pepe', 1, 'febrero')

print(dic1)
print(dic2)

### Generadores

Escribe un generador que reciba una lista y genere todas las permutaciones que se puedan hacer con los elementos de la lista

In [ ]:

# Escribe aqui fun1
import itertools

permutations = itertools.permutations(lista)
for permutaciones in permutations:
    print(permutaciones)



(1, 'a', 1, 13, 'hola', 'a', 1, 1, 'a', 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 1, 'a')
(1, 'a', 1, 13, 'hola', 'a', 1, 'a', 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 'a', 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 1, 'a')
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 'a', 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 'a', 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 1, 'a')
(1, 'a', 1, 13, 'hola', 'a', 1, 'a', 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 'a', 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 1, 'a')
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 'a', 1)
(1, 'a', 1, 13, 'hola', 'a', 'a', 1, 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 'a', 1, 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 'a', 1, 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 'a', 1, 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 'a', 1, 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 'a', 1, 1, 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 1, 'a')
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 'a', 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 1, 'a')
(1, 'a', 1, 13, 'hola', 'a', 1, 1, 'a', 1)
(1, 'a', 1, 13, 'hola', 'a', 1, 'a', 1, 1)
(1, 'a', 1,

KeyboardInterrupt: 

In [ ]:
# Realiza pruebas de fun2 aquí


Ahora escribe una funcipn que reciba 4 digitos del 0 al 9, y devuelva una lista con todas las horas váidas que se puedan hacer con estos dígitos en forma de lista de strings con la forma `"HH:MM"`.

In [ ]:
#importar módulo
import itertools

#definición de la los elementos
Num = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#definir límites en horas y minutos
def is_valid_time(perm):
    hours = int(perm[0] + perm[1])
    minutes = int(perm[2] + perm[3])
    return 0 <= hours < 24 and 0 <= minutes < 60

#programar las permutaciones
def time_evaluation(digits):
    myPermutations = itertools.permutations(digits)
    valid_times = set()
    for perm in myPermutations:
        perm_str = ''.join(map(str, perm))
        if is_valid_time(perm_str):
            times = perm_str[0] + perm_str[1] + ":" + perm_str[2] + perm_str[3]
            valid_times.add(times)
    return valid_times

#generar las horas válidas
valid_time = time_evaluation(Num)
for time in valid_time:
    print(time)

04:31
18:42
17:09
12:05
20:34
03:18
03:52
13:09
01:35
17:48
04:23
23:51
03:54
13:26
12:36
19:45
05:36
06:15
03:21
01:49
17:56
18:57
05:16
07:53
08:24
04:26
13:07
06:12
14:50
01:43
15:30
19:53
10:39
05:28
09:18
18:36
21:57
02:37
08:46
01:34
10:52
07:12
16:28
10:54
08:19
19:07
15:47
08:45
10:59
06:31
19:23
12:06
09:16
06:14
20:18
10:46
17:29
09:15
15:48
23:08
05:48
21:58
20:45
17:54
19:26
01:46
17:26
13:02
21:05
09:13
16:37
05:47
06:57
04:56
14:25
07:32
01:37
23:06
21:48
12:04
14:52
16:39
10:57
13:49
06:48
21:47
01:24
12:35
20:49
07:54
17:38
02:18
18:34
07:31
02:56
16:59
04:21
09:32
06:58
08:57
09:28
03:17
07:51
19:30
10:35
18:49
17:32
20:36
14:02
02:43
08:31
23:19
16:52
08:36
17:23
16:05
03:51
18:45
09:37
07:58
09:54
06:52
16:29
19:47
15:26
12:45
12:49
08:23
06:25
14:58
21:03
20:48
02:58
15:34
15:07
08:27
17:53
15:43
13:20
01:36
10:25
08:14
18:20
21:38
19:25
05:42
21:49
21:50
13:46
15:40
02:34
15:03
16:48
21:37
13:29
23:54
09:31
07:52
18:37
01:57
10:38
06:49
21:59
13:06
04:36
20:19
01:5

Validando:

In [ ]:
print(horas_validas([1,2,3,4]))

None


Escribe una función, lo más compacta posible, que escoja entre los 3 patrones ascii a continuación, e imprima en pantalla
el deseado, pero de dimensión $n$ ($n \ge 4$), toma en cuanta que para algunos valores de $n$ habrá
algún(os) patrones que no se puedan hacer.

```
          *             ++++           oooooooo
          **            ++++           ooo  ooo
          ***           ++++           oo    oo
          ****          ++++           o      o
          *****             ++++       o      o
          ******            ++++       oo    oo
          *******           ++++       ooo  ooo
          ********          ++++       oooooooo

```

In [ ]:
# Escribe aquí la función

In [ ]:
#Realiza pruebas aquí


### Clases y objetos

Diseña una clase Matriz con las siguientes características:

1. Como inicialización de un objeto es necesario conocer $n$, $m$ y tipo. En caso de no proporcionar $m$ la matriz se asume cuadrada de $n \times n$. En caso de no proporcionar $n$ la matriz tendrá una dimensión de $1 \times 1$.
2. De no especificarse todos los elementos se inicializan a 0, a menos que exista un tipo especial ( `unos` o `diag` por el momento).
3. Implementa con sobrecarga la suma de matrices, la multiplicación de matrices y la multiplicación por un escalar.
4. Implementa como métodos eliminar columna y eliminar fila.   
5. Programa la representación visual de la matriz.
6. Ten en cuenta tambien el manejo de errores.


Ejemplo de uso:

```
>>> A = Matriz(n=3, m=4)

>>> print(A)
0 0 0 0
0 0 0 0
0 0 0 0

>>> A = A.quitafila(2)

>>> print(A)
0 0 0 0
0 0 0 0

>>> B = Matriz(4,4,'diag')

>>> print(B)
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 1

>>> C = Matriz(4,1,'unos')

>>> print(C)
1
1
1
1

>>> D = 3 * B * C

>>> print(D)
3
3
3
3

>>> E = 3 * B + C
error "No seas menso, si no son de la misma dimensión las matrices no se pueden sumar"
```

In [ ]:
# Desarrolla aqui la clase

import numpy

A = numpy.array([[0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4], [0, 1, 2, 3, 4]])
print(A)

B = numpy.array([[0, 4, 2, 1, 4], [0, 1, 2, 4, 4], [0, 1, 2, 3, 4], [0, 6, 2, 3, 4], [0, 2, 2, 3, 4]])
print(B)

import numpy as np
suma = np.array(A)+np.array(B)
multi = np.dot(A,B)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 4 2 1 4]
 [0 1 2 4 4]
 [0 1 2 3 4]
 [0 6 2 3 4]
 [0 2 2 3 4]]


In [ ]:
# Realiza las pruebas a la clase aquí

A = Matriz(n=3, m=4)
print('A =', A)

A = A.quitafila(2)
print('A = ', A)

B = Matriz(4,4,'diag')
print('B = ', B)

C = Matriz(4,1,'unos')
print('C =', C)

D = 3 * B * C
print('D = ', D)

E = 3 * B + C
print('E = ', E)

NameError: name 'Matriz' is not defined